- hosts: local
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Pull calculator image
      community.docker.docker_image:
        name: "docker.io/tah1rthet1ger/scientific-calculator:latest"
        source: pull

    - name: Run calculator container (detached)
      community.docker.docker_container:
        name: calc
        image: "docker.io/tah1rthet1ger/scientific-calculator:latest"
        state: started
        restart_policy: unless-stopped
        tty: true
        interactive: true
        detach: true
